using Blessing.Core;
using Blessing.Core.ScriptableObjectDropdown;
using Blessing.GameData;
using System.Threading.Tasks;
using UnityEngine;
using UnitySceneManager = UnityEngine.SceneManagement.SceneManager;

namespace Blessing.Services
{
    class MainMenuHandler : MonoBehaviour
    {
        // [ScriptableObjectDropdown(typeof(SceneReference))] public ScriptableObjectReference SinglePlayerScene;
        // private SceneReference singlePlayerScene { get { return SinglePlayerScene.value as SceneReference; } }
        // public SceneReference FirstSinglePlayerScene { get { return singlePlayerScene;}}
        [ScriptableObjectDropdown(typeof(SceneReference))] public ScriptableObjectReference MultiplayerScene;
        private SceneReference multiplayerScene { get { return MultiplayerScene.value as SceneReference; } }
        
        void Start()
        {
            GameplayEventHandler.OnConnectToSessionCompleted += OnConnectToSessionCompleted;
        }

        void OnDestroy()
        {
            GameplayEventHandler.OnConnectToSessionCompleted -= OnConnectToSessionCompleted;
        }

        public void OnConnectToSessionCompleted(Task task)
        {
            if (task.IsCompletedSuccessfully)
            {
                Debug.Log("ConnectToSessionCompleted");

                // Descarregar a cena presente, que deve ser o menu.
                // SceneManager.Singleton.Unload(SceneManager.Singleton.CurrentScene);
                UnitySceneManager.UnloadSceneAsync(SceneManager.Singleton.CurrentScene.SceneName);

                if (GameDataManager.Singleton.IsHost)
                {
                    // Quando host carregar a cena, todos os clientes carregar√£o junto.
                    SceneManager.Singleton.LoadAsync(multiplayerScene); 
                }
            }
        }
    }
}
